<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [2]:
import os

In [1]:
import numpy as np

In [4]:
datos = os.listdir()
datos

['laboratorio-modulo2-leccion01-numpy.ipynb',
 'laboratorio-modulo2-leccion05-limpieza.ipynb',
 'laboratorio-modulo2-leccion04-visualizacion.ipynb',
 'laboratorio-modulo2-leccion03-groupby.ipynb',
 'laboratorio-modulo2-leccion02-eda-union.ipynb',
 'laboratorio-modulo2-leccion03-filtrado.ipynb']

In [ ]:
diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}

diccioanrio_df = {}
for i in datos:
    df = pd.read_csv(i)
    diccioanrio_df[i.spl]


for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [3]:
array_unidimensional_arange_1 =  np.arange(10)
array_unidimensional_arange_1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [5]:
reshaped = np.reshape(array_unidimensional_arange_1, (2, 5))
reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [7]:
lista = [0, 2, 0, 3, 0, 4, 0]
array2 = np.array(lista)
resultado_where = np.where(array2 != 0)
resultado_where

(array([1, 3, 5]),)

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [8]:
array_rand_bi = np.random.rand(3,3)
array_rand_bi

array([[0.32459501, 0.11031209, 0.52733172],
       [0.82324168, 0.85947553, 0.09824363],
       [0.54644395, 0.64167902, 0.00438682]])

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [11]:
array_rand_uni = np.random.rand(10)
array_rand_uni
minimo = np.min(array_rand_uni)
maximo = np.max(array_rand_uni)
print(f'El array es {array_rand_uni}')
print(f'El valor mínimo es {minimo}')
print(f'El valor máximo es {maximo}')


El array es [0.38822824 0.05806055 0.58127105 0.52372174 0.72082384 0.1809888
 0.71530431 0.12491836 0.19180282 0.71202967]
El valor mínimo es 0.05806054765134705
El valor máximo es 0.7208238364338065


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [16]:
array_randint_tri = np.random.randint(1, 25, (2,3, 4))
array_randint_tri

array([[[11, 16,  8,  8],
        [11,  5, 17, 15],
        [17,  6, 24, 23]],

       [[12,  4,  7, 17],
        [ 8, 15,  1, 18],
        [24, 13,  2, 20]]])

In [17]:
array_randint_tri[0,1,3]

np.int64(15)

In [18]:
array_randint_tri[0]

array([[11, 16,  8,  8],
       [11,  5, 17, 15],
       [17,  6, 24, 23]])

In [19]:
array_randint_tri[1,2]

array([24, 13,  2, 20])


#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [20]:
array_randint_tri2 = np.random.randint(1, 31, (3,2, 5))
array_randint_tri2


array([[[ 3, 15,  8, 21, 12],
        [ 7, 30, 22,  5, 10]],

       [[13,  4,  3, 27, 24],
        [15, 20, 15, 26, 24]],

       [[25, 14, 15,  3, 18],
        [24, 26, 24, 11,  3]]])

In [21]:
array_randint_tri2[0,:,:2]

array([[ 3, 15],
       [ 7, 30]])

In [22]:
array_randint_tri2[1:]

array([[[13,  4,  3, 27, 24],
        [15, 20, 15, 26, 24]],

       [[25, 14, 15,  3, 18],
        [24, 26, 24, 11,  3]]])

#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [23]:
array_randint_tri3 = np.random.randint(1, 25, (4,3,2))
array_randint_tri3


array([[[16, 22],
        [19, 19],
        [12, 12]],

       [[22, 10],
        [ 1, 17],
        [22, 22]],

       [[23, 17],
        [16,  3],
        [24,  5]],

       [[14,  8],
        [ 3,  4],
        [ 1,  2]]])

In [26]:
array_randint_tri3[1,1] = 0
array_randint_tri3[1,1]

array([0, 0])

In [27]:
array_randint_tri3[3] = -1
array_randint_tri3[3]

array([[-1, -1],
       [-1, -1],
       [-1, -1]])

In [28]:
array_randint_tri3

array([[[16, 22],
        [19, 19],
        [12, 12]],

       [[22, 10],
        [ 0,  0],
        [22, 22]],

       [[23, 17],
        [16,  3],
        [24,  5]],

       [[-1, -1],
        [-1, -1],
        [-1, -1]]])


#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [30]:
array_randint_tri4 = np.random.randint(-10, 14, (2,4,3))
array_randint_tri4


array([[[  5,   6,  -8],
        [  6,  -1,   2],
        [ -4,   6,  -5],
        [ -3, -10, -10]],

       [[ -5,  11, -10],
        [ -2,  -4,   4],
        [  7,   3,  13],
        [ -7,  -3,   7]]])

In [35]:
mayores5 = array_randint_tri4[array_randint_tri4 > 5]
mayores5

array([ 6,  6,  6, 11,  7, 13,  7])

In [36]:
array_randint_tri4[array_randint_tri4 < 0] = 0
array_randint_tri4

array([[[ 5,  6,  0],
        [ 6,  0,  2],
        [ 0,  6,  0],
        [ 0,  0,  0]],

       [[ 0, 11,  0],
        [ 0,  0,  4],
        [ 7,  3, 13],
        [ 0,  0,  7]]])

#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [37]:
array_randint_tri5 = np.random.randint(1, 28, (3,3,3))
array_randint_tri5

array([[[11, 18, 11],
        [ 2,  9, 17],
        [13, 19, 27]],

       [[23,  7,  8],
        [14, 20, 15],
        [ 5, 12,  9]],

       [[20,  7,  6],
        [20, 10, 15],
        [20,  1, 27]]])

In [38]:
array_randint_tri5[1,:,:2]

array([[23,  7],
       [14, 20],
       [ 5, 12]])

In [44]:
mayores20 = array_randint_tri5[array_randint_tri5 > 20]
mayores20

array([27, 23, 27])

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [46]:
array_random = np.random.rand(10)
array_random

array([0.63620654, 0.50559446, 0.53327484, 0.22758817, 0.29666955,
       0.86349879, 0.96654835, 0.79050641, 0.2222838 , 0.36679793])

In [50]:
maximo1 = np.argmax(array_random)
minimo1 = np.argmin(array_random)
array_random[maximo1] = 0
array_random[minimo1] = 0
array_random

array([0.63620654, 0.50559446, 0.53327484, 0.22758817, 0.29666955,
       0.        , 0.        , 0.79050641, 0.        , 0.36679793])

#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [53]:
array_random2 = np.random.randint(1, 101, size=15)
array_ordenado = np.sort(array_random2)
array_ordenado


array([16, 19, 22, 28, 29, 31, 41, 48, 49, 68, 76, 82, 85, 97, 99])

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [55]:
random3 = np.random.randint(1, 11, (4, 4))
random3

array([[10, 10,  8, 10],
       [ 8,  1,  7, 10],
       [ 7,  4,  6,  5],
       [ 5,  4,  1,  9]])

In [57]:
suma_filas = np.sum(random3, axis=1)
suma_filas

array([38, 26, 22, 19])

In [59]:
suma_columnas = np.sum(random3, axis=0)
suma_columnas


array([30, 19, 22, 34])

#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [62]:
array_ceros = np.zeros((5, 5), dtype=int)
array_ceros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [63]:
array_ceros[0, :] = 1 
array_ceros[-1, :] = 1 
array_ceros[:, 0] = 1
array_ceros[:, -1] = 1
array_ceros

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [64]:
random4 = np.random.randint(0, 101, 10)
random4

array([16, 34, 67, 26, 49, 56, 88, 99,  0,  6])

In [65]:
media = np.mean(random4)
media

np.float64(44.1)

In [66]:
desviacion_estandar = np.std(random4)
desviacion_estandar


np.float64(32.01077943443427)

#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [67]:
array_randint_tri6 = np.random.randint(1, 25, (2,3,4))
array_randint_tri6

array([[[ 6,  9,  2, 23],
        [23, 17, 24, 24],
        [ 6,  2, 10, 16]],

       [[11, 15,  8, 10],
        [19, 17, 23, 14],
        [ 1, 23,  7, 12]]])

In [68]:
array_trans = np.transpose(array_randint_tri6, (4, 3, 2))
array_trans

AxisError: axis 4 is out of bounds for array of dimension 3

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.